function result = isANumericClassName(className)
    result = ...
        isequal(className,'double') || ...            
        isequal(className,'single') || ...
        isequal(className,'int8') || ...
        isequal(className,'uint8') || ...
        isequal(className,'int16') || ...
        isequal(className,'uint16') || ...
        isequal(className,'int32') || ...
        isequal(className,'uint32') || ...
        isequal(className,'int64') || ...
        isequal(className,'uint64') ;
end
