function result = updateAnalogScalingCoefficientsCache(originalAnalogScalingCoefficientsCache, ...
                                                       analogChannelIndex, ...
                                                       originalIsAnalogChannelActiveFromAnalogChannelIndex, ...
                                                       newIsSingleChannelActive)
    % analogScalingCoefficientsCache is nCoefficients x nChannels                                               
    if newIsSingleChannelActive ,
        newIsAnalogChannelActiveFromAnalogChannelIndex = ws.replace(originalIsAnalogChannelActiveFromAnalogChannelIndex, ...
                                                                    analogChannelIndex, ...
                                                                    true) ;
        newActiveAIChannelIndexFromAnalogChannelIndex = ...
            ws.computeActiveChannelIndexFromChannelIndex(newIsAnalogChannelActiveFromAnalogChannelIndex) ;
        newActiveAnalogChannelIndex = newActiveAIChannelIndexFromAnalogChannelIndex(analogChannelIndex) ;
        coefficientCount = size(originalAnalogScalingCoefficientsCache, 1) ;
        result = ws.insertColumn(originalAnalogScalingCoefficientsCache, newActiveAnalogChannelIndex, nan(coefficientCount,1)) ;
    else
        originalActiveAIChannelIndexFromAIChannelIndex = ...
            ws.computeActiveChannelIndexFromChannelIndex(originalIsAnalogChannelActiveFromAnalogChannelIndex) ;
        originalActiveAnalogChannelIndex = originalActiveAIChannelIndexFromAIChannelIndex(analogChannelIndex) ;
        result = ws.deleteColumns(originalAnalogScalingCoefficientsCache, originalActiveAnalogChannelIndex) ;        
    end
end
