function result = updateBitsAfterIsDigitalChannelActiveChange(originalOneBitPerActiveDigitalChannel, ...
                                                              digitalChannelIndex, ...
                                                              originalIsDigitalChannelActiveFromDigitalChannelIndex, ...
                                                              newIsSingleChannelActive)
    % originalOneColumnPerActiveDigitalChannel is nRows x nActiveChannels                                               
    originalActiveDigitalChannelCount = sum(originalIsDigitalChannelActiveFromDigitalChannelIndex) ;
    if newIsSingleChannelActive ,
        newIsDigitalChannelActiveFromDigitalChannelIndex = ws.replace(originalIsDigitalChannelActiveFromDigitalChannelIndex, ...
                                                                      digitalChannelIndex, ...
                                                                      true) ;
        newActiveDigitalChannelIndexFromDigitalChannelIndex = ...
            ws.computeActiveChannelIndexFromChannelIndex(newIsDigitalChannelActiveFromDigitalChannelIndex) ;
        newActiveDigitalChannelIndex = newActiveDigitalChannelIndexFromDigitalChannelIndex(digitalChannelIndex) ;
        rowCount = size(originalOneBitPerActiveDigitalChannel, 1) ;
        result = ws.insertBitColumn(originalOneBitPerActiveDigitalChannel, newActiveDigitalChannelIndex, originalActiveDigitalChannelCount, false(rowCount,1)) ;
    else
        originalActiveAIChannelIndexFromAIChannelIndex = ...
            ws.computeActiveChannelIndexFromChannelIndex(originalIsDigitalChannelActiveFromDigitalChannelIndex) ;
        originalActiveDigitalChannelIndex = originalActiveAIChannelIndexFromAIChannelIndex(digitalChannelIndex) ;
        result = ws.deleteBitColumns(originalOneBitPerActiveDigitalChannel, originalActiveDigitalChannelIndex, originalActiveDigitalChannelCount) ;        
    end
end
