classdef PezController < handle
    
    properties (Dependent)
        FigurePosition
    end
    
    properties (Access=private)
        Model_
        Figure_
        
        TrialSequenceModeLabel_
        TrialSequenceModePopupMenu_
        ReturnDelayLabelledEdit_
        ResetButton_

        TapCountLabelledEdit_
        DispenseSpeedXLabelledEdit_
        DispenseSpeedYLabelledEdit_
        DispenseSpeedZLabelledEdit_
        MaximumRunLengthLabelledEdit_
        LaserTrialSpacingLabelledEdit_
        
        Condition1Label_
        ToneFrequency1LabelledEdit_
        ToneDuration1LabelledEdit_
        ToneDelay1LabelledEdit_
        DispenseDelay1LabelledEdit_
        DeliverPosition1XLabelledEdit_
        DeliverPosition1YLabelledEdit_
        DeliverPosition1ZLabelledEdit_        
        DispensePosition1XLabelledEdit_
        DispensePosition1YLabelledEdit_
        DispensePosition1ZLabelledEdit_
        
        Condition2Label_
        ToneFrequency2LabelledEdit_
        ToneDuration2LabelledEdit_
        ToneDelay2LabelledEdit_
        DispenseDelay2LabelledEdit_
        DeliverPosition2XLabelledEdit_
        DeliverPosition2YLabelledEdit_
        DeliverPosition2ZLabelledEdit_        
        DispensePosition2XLabelledEdit_                
        DispensePosition2YLabelledEdit_                
        DispensePosition2ZLabelledEdit_                
    end

    methods
        function self = PezController(model)
            self.Model_ = model ;
            fig = figure('Name', 'Pez', ...
                         'MenuBar', 'none', ...
                         'IntegerHandle', 'off', ...
                         'Resize', 'off', ...
                         'CloseRequestFcn', @(source, event)(ws.nop()), ...
                         'HandleVisibility', 'off') ;
                % Make the figure un-closable, since no way to get it back if it gets closed...     
            self.Figure_ = fig ;
            
            % First row (from top)
            self.TrialSequenceModeLabel_ = ...
                ws.uicontrol('Parent', fig, ...
                             'Style', 'text', ...
                             'String', 'Mode:') ;
            self.TrialSequenceModePopupMenu_ = ...
                ws.uipopupmenu(...
                    'Parent', fig, ...
                    'Tag', 'TrialSequenceMode', ...
                    'Callback', @(source,event)(self.controlActuated(source, event)), ...
                    'String',{'<borkenness>'}, ...
                    'Value',1) ;            
            self.ReturnDelayLabelledEdit_ = ...
                ws.LabelledEdit('Parent', fig, ...
                                         'Tag', 'ReturnDelay', ...
                                         'Callback', @(source,event)(self.controlActuated(source, event)), ...
                                         'HorizontalAlignment', 'right', ...
                                         'LabelString', 'Return Delay:', ...
                                         'UnitsString', 's') ;            
            self.ResetButton_ = ...
                ws.uicontrol('Parent', fig, ...
                             'Tag', 'ResetButton', ...
                             'Callback', @(source,event)(self.controlActuated(source, event)), ...
                             'Style', 'pushbutton', ...
                             'String', 'Reset') ;                
                
            self.TapCountLabelledEdit_ = ...
                ws.LabelledEdit('Parent', fig, ...
                                         'Tag', 'TapCount', ...
                                         'Callback', @(source,event)(self.controlActuated(source, event)), ...
                                         'HorizontalAlignment', 'right', ...
                                         'LabelString', 'Tap Count:', ...
                                         'UnitsString', '') ;            

            self.DispenseSpeedXLabelledEdit_ = ...
                ws.LabelledEdit('Parent', fig, ...
                                         'Tag', 'DispenseSpeedX', ...
                                         'Callback', @(source,event)(self.controlActuated(source, event)), ...
                                         'HorizontalAlignment', 'right', ...
                                         'LabelString', 'Dispense Speed X:') ;
            self.DispenseSpeedYLabelledEdit_ = ...
                ws.LabelledEdit('Parent', fig, ...
                                         'Tag', 'DispenseSpeedY', ...
                                         'Callback', @(source,event)(self.controlActuated(source, event)), ...
                                         'HorizontalAlignment', 'right', ...
                                         'LabelString', 'Dispense Speed Y:') ;
            self.DispenseSpeedZLabelledEdit_ = ...
                ws.LabelledEdit('Parent', fig, ...
                                         'Tag', 'DispenseSpeedZ', ...
                                         'Callback', @(source,event)(self.controlActuated(source, event)), ...
                                         'HorizontalAlignment', 'right', ...
                                         'LabelString', 'Dispense Speed Z:') ;                                     
                                     
            self.MaximumRunLengthLabelledEdit_ = ...
                ws.LabelledEdit('Parent', fig, ...
                                         'Tag', 'RandomTrialSequenceMaximumRunLength', ...
                                         'Callback', @(source,event)(self.controlActuated(source, event)), ...
                                         'HorizontalAlignment', 'right', ...
                                         'LabelString', 'Maximum Run Length:', ...
                                         'UnitsString', 'trials') ;            

            self.LaserTrialSpacingLabelledEdit_ = ...
                ws.LabelledEdit('Parent', fig, ...
                                         'Tag', 'RandomTrialSequenceLaserTrialSpacing', ...
                                         'Callback', @(source,event)(self.controlActuated(source, event)), ...
                                         'HorizontalAlignment', 'right', ...
                                         'LabelString', 'Laser Trial Spacing:', ...
                                         'UnitsString', 'trials') ;            


                         
            % Per-condition columns                                     
            self.Condition1Label_ = ...
                ws.uicontrol('Parent', fig, ...
                             'Tag', 'Condition1', ...
                             'Style', 'text', ...
                             'String', 'Condition 1') ;                                         
            self.ToneFrequency1LabelledEdit_ = ...
                ws.LabelledEdit('Parent', fig, ...
                                         'Tag', 'ToneFrequency1', ...
                                         'Callback', @(source,event)(self.controlActuated(source, event)), ...
                                         'HorizontalAlignment', 'right', ...
                                         'LabelString', 'Tone Frequency:', ...
                                         'UnitsString', 'Hz') ;
            self.ToneDelay1LabelledEdit_ = ...
                ws.LabelledEdit('Parent', fig, ...
                                         'Tag', 'ToneDelay1', ...
                                         'Callback', @(source,event)(self.controlActuated(source, event)), ...
                                         'HorizontalAlignment', 'right', ...
                                         'LabelString', 'Tone Delay:', ...
                                         'UnitsString', 's') ;
            self.ToneDuration1LabelledEdit_ = ...
                ws.LabelledEdit('Parent', fig, ...
                                         'Tag', 'ToneDuration1', ...
                                         'Callback', @(source,event)(self.controlActuated(source, event)), ...
                                         'HorizontalAlignment', 'right', ...
                                         'LabelString', 'Tone Duration:', ...
                                         'UnitsString', 's') ;
            self.DispenseDelay1LabelledEdit_ = ...
                ws.LabelledEdit('Parent', fig, ...
                                         'Tag', 'DispenseDelay1', ...
                                         'Callback', @(source,event)(self.controlActuated(source, event)), ...
                                         'HorizontalAlignment', 'right', ...
                                         'LabelString', 'Dispense Delay:', ...
                                         'UnitsString', 's') ;
            self.DeliverPosition1XLabelledEdit_ = ...
                ws.LabelledEdit('Parent', fig, ...
                                         'Tag', 'DeliverPosition1X', ...
                                         'Callback', @(source,event)(self.controlActuated(source, event)), ...
                                         'HorizontalAlignment', 'right', ...
                                         'LabelString', 'Delivery X:', ...
                                         'UnitsString', '') ;
            self.DeliverPosition1YLabelledEdit_ = ...
                ws.LabelledEdit('Parent', fig, ...
                                         'Tag', 'DeliverPosition1Y', ...
                                         'Callback', @(source,event)(self.controlActuated(source, event)), ...
                                         'HorizontalAlignment', 'right', ...
                                         'LabelString', 'Delivery Y:', ...
                                         'UnitsString', '') ;
            self.DeliverPosition1ZLabelledEdit_ = ...
                ws.LabelledEdit('Parent', fig, ...
                                         'Tag', 'DeliverPosition1Z', ...
                                         'Callback', @(source,event)(self.controlActuated(source, event)), ...
                                         'HorizontalAlignment', 'right', ...
                                         'LabelString', 'Delivery Z:', ...
                                         'UnitsString', '') ;
            self.DispensePosition1XLabelledEdit_ = ...
                ws.LabelledEdit('Parent', fig, ...
                                         'Tag', 'DispensePosition1X', ...
                                         'Callback', @(source,event)(self.controlActuated(source, event)), ...
                                         'HorizontalAlignment', 'right', ...
                                         'LabelString', 'Dispense X:', ...
                                         'UnitsString', '') ;
            self.DispensePosition1YLabelledEdit_ = ...
                ws.LabelledEdit('Parent', fig, ...
                                         'Tag', 'DispensePosition1Y', ...
                                         'Callback', @(source,event)(self.controlActuated(source, event)), ...
                                         'HorizontalAlignment', 'right', ...
                                         'LabelString', 'Dispense Y:', ...
                                         'UnitsString', '') ;
            self.DispensePosition1ZLabelledEdit_ = ...
                ws.LabelledEdit('Parent', fig, ...
                                         'Tag', 'DispensePosition1Z', ...
                                         'Callback', @(source,event)(self.controlActuated(source, event)), ...
                                         'HorizontalAlignment', 'right', ...
                                         'LabelString', 'Dispense Z:', ...
                                         'UnitsString', '') ;
                                     
            self.Condition2Label_ = ...
                ws.uicontrol('Parent', fig, ...
                             'Tag', 'Condition2', ...
                             'Style', 'text', ...
                             'String', 'Condition 2') ;
            self.ToneFrequency2LabelledEdit_ = ...
                ws.LabelledEdit('Parent', fig, ...
                                         'Tag', 'ToneFrequency2', ...
                                         'Callback', @(source,event)(self.controlActuated(source, event)), ...
                                         'HorizontalAlignment', 'right', ...
                                         'LabelString', '', ...
                                         'UnitsString', 'Hz') ;
            self.ToneDelay2LabelledEdit_ = ...
                ws.LabelledEdit('Parent', fig, ...
                                         'Tag', 'ToneDelay2', ...
                                         'Callback', @(source,event)(self.controlActuated(source, event)), ...
                                         'HorizontalAlignment', 'right', ...
                                         'LabelString', '', ...
                                         'UnitsString', 's') ;
            self.ToneDuration2LabelledEdit_ = ...
                ws.LabelledEdit('Parent', fig, ...
                                         'Tag', 'ToneDuration2', ...
                                         'Callback', @(source,event)(self.controlActuated(source, event)), ...
                                         'HorizontalAlignment', 'right', ...
                                         'LabelString', '', ...
                                         'UnitsString', 's') ;
            self.DispenseDelay2LabelledEdit_ = ...
                ws.LabelledEdit('Parent', fig, ...
                                         'Tag', 'DispenseDelay2', ...
                                         'Callback', @(source,event)(self.controlActuated(source, event)), ...
                                         'HorizontalAlignment', 'right', ...
                                         'LabelString', '', ...
                                         'UnitsString', 's') ;
            self.DeliverPosition2XLabelledEdit_ = ...
                ws.LabelledEdit('Parent', fig, ...
                                         'Tag', 'DeliverPosition2X', ...
                                         'Callback', @(source,event)(self.controlActuated(source, event)), ...
                                         'HorizontalAlignment', 'right', ...
                                         'LabelString', '', ...
                                         'UnitsString', '') ;
            self.DeliverPosition2YLabelledEdit_ = ...
                ws.LabelledEdit('Parent', fig, ...
                                         'Tag', 'DeliverPosition2Y', ...
                                         'Callback', @(source,event)(self.controlActuated(source, event)), ...
                                         'HorizontalAlignment', 'right', ...
                                         'LabelString', '', ...
                                         'UnitsString', '') ;
            self.DeliverPosition2ZLabelledEdit_ = ...
                ws.LabelledEdit('Parent', fig, ...
                                         'Tag', 'DeliverPosition2Z', ...
                                         'Callback', @(source,event)(self.controlActuated(source, event)), ...
                                         'HorizontalAlignment', 'right', ...
                                         'LabelString', '', ...
                                         'UnitsString', '') ;
            self.DispensePosition2XLabelledEdit_ = ...
                ws.LabelledEdit('Parent', fig, ...
                                         'Tag', 'DispensePosition2X', ...
                                         'Callback', @(source,event)(self.controlActuated(source, event)), ...
                                         'HorizontalAlignment', 'right', ...
                                         'LabelString', '', ...
                                         'UnitsString', '') ;
            self.DispensePosition2YLabelledEdit_ = ...
                ws.LabelledEdit('Parent', fig, ...
                                         'Tag', 'DispensePosition2Y', ...
                                         'Callback', @(source,event)(self.controlActuated(source, event)), ...
                                         'HorizontalAlignment', 'right', ...
                                         'LabelString', '', ...
                                         'UnitsString', '') ;
            self.DispensePosition2ZLabelledEdit_ = ...
                ws.LabelledEdit('Parent', fig, ...
                                         'Tag', 'DispensePosition2Z', ...
                                         'Callback', @(source,event)(self.controlActuated(source, event)), ...
                                         'HorizontalAlignment', 'right', ...
                                         'LabelString', '', ...
                                         'UnitsString', '') ;
                                                              
            model.registerController(self) ;
            self.layout_() ;
            self.update() ;
        end
        
        function delete(self)
            if ~isempty(self.Figure_) && ishandle(self.Figure_) ,
                delete(self.Figure_) ;
            end
        end

        function controlActuated(self, source, event)  %#ok<INUSD>
            try
                if source==self.ResetButton_ ,
                    self.Model_.reset() ;
                else
                    % Must be a case where we want to set a model property
                    if source==self.TrialSequenceModePopupMenu_ ,
                        propertyName = 'TrialSequenceMode' ;
                        newValue = ws.getPopupMenuSelection(source, self.Model_.TrialSequenceModeOptions) ;
                    elseif isequal(source.Style, 'checkbox') ;
                        tag = source.Tag ;
                        propertyName = tag ;
                        newValue = source.Value ;
                    else
                        % Must be an edit
                        tag = source.Tag ;
                        propertyName = tag ;
                        rawNewValue = source.String ;
                        newValue = str2double(rawNewValue) ;
                    end
                    % Attempt to set the property name in the model
                    self.Model_.(propertyName) = newValue ;
                end
            catch exception
                self.update() ;  % If an exception is throw, the PezUserClass will generally not tell the controller to update
                if isequal(exception.identifier, 'ws:invalidPropertyValue') ,
                    % do nothing
                else
                    % raise a dialog
                    ws.raiseDialogOnException(exception) ;
                end
            end                                
        end  % function
        
        function update(self)
            % Update values
            ws.setPopupMenuItemsAndSelectionBang(self.TrialSequenceModePopupMenu_, ...
                                                 self.Model_.TrialSequenceModeOptions, ...
                                                 self.Model_.TrialSequenceMode) ;
            self.ReturnDelayLabelledEdit_.EditString = sprintf('%g', self.Model_.ReturnDelay) ;                        
            
            self.TapCountLabelledEdit_.EditString = sprintf('%g', self.Model_.TapCount) ;
            self.DispenseSpeedXLabelledEdit_.EditString = sprintf('%g', self.Model_.DispenseSpeedX) ;
            self.DispenseSpeedYLabelledEdit_.EditString = sprintf('%g', self.Model_.DispenseSpeedY) ;
            self.DispenseSpeedZLabelledEdit_.EditString = sprintf('%g', self.Model_.DispenseSpeedZ) ;
            self.MaximumRunLengthLabelledEdit_.EditString = sprintf('%g', self.Model_.RandomTrialSequenceMaximumRunLength) ;
            self.LaserTrialSpacingLabelledEdit_.EditString = sprintf('%g', self.Model_.RandomTrialSequenceLaserTrialSpacing) ;
            
            self.ToneFrequency1LabelledEdit_.EditString = sprintf('%g', self.Model_.ToneFrequency1) ;                        
            self.ToneDelay1LabelledEdit_.EditString = sprintf('%g', self.Model_.ToneDelay1) ;
            self.ToneDuration1LabelledEdit_.EditString = sprintf('%g', self.Model_.ToneDuration1) ;
            self.DispenseDelay1LabelledEdit_.EditString = sprintf('%g', self.Model_.DispenseDelay1) ;
            self.DeliverPosition1XLabelledEdit_.EditString = sprintf('%g', self.Model_.DeliverPosition1X) ;            
            self.DeliverPosition1YLabelledEdit_.EditString = sprintf('%g', self.Model_.DeliverPosition1Y) ;            
            self.DeliverPosition1ZLabelledEdit_.EditString = sprintf('%g', self.Model_.DeliverPosition1Z) ;            
            self.DispensePosition1XLabelledEdit_.EditString = sprintf('%g', self.Model_.DispensePosition1X) ;                        
            self.DispensePosition1YLabelledEdit_.EditString = sprintf('%g', self.Model_.DispensePosition1Y) ;                        
            self.DispensePosition1ZLabelledEdit_.EditString = sprintf('%g', self.Model_.DispensePosition1Z) ;                        
            
            self.ToneFrequency2LabelledEdit_.EditString = sprintf('%g', self.Model_.ToneFrequency2) ;                        
            self.ToneDelay2LabelledEdit_.EditString = sprintf('%g', self.Model_.ToneDelay2) ;
            self.ToneDuration2LabelledEdit_.EditString = sprintf('%g', self.Model_.ToneDuration2) ;
            self.DispenseDelay2LabelledEdit_.EditString = sprintf('%g', self.Model_.DispenseDelay2) ;
            self.DeliverPosition2XLabelledEdit_.EditString = sprintf('%g', self.Model_.DeliverPosition2X) ;            
            self.DeliverPosition2YLabelledEdit_.EditString = sprintf('%g', self.Model_.DeliverPosition2Y) ;            
            self.DeliverPosition2ZLabelledEdit_.EditString = sprintf('%g', self.Model_.DeliverPosition2Z) ;            
            self.DispensePosition2XLabelledEdit_.EditString = sprintf('%g', self.Model_.DispensePosition2X) ;
            self.DispensePosition2YLabelledEdit_.EditString = sprintf('%g', self.Model_.DispensePosition2Y) ;
            self.DispensePosition2ZLabelledEdit_.EditString = sprintf('%g', self.Model_.DispensePosition2Z) ;

            % Update enablement
            self.TrialSequenceModePopupMenu_.Enable = ws.onIff(~self.Model_.IsRunning) ;
            self.ReturnDelayLabelledEdit_.Enable = ws.onIff(true) ;            
            self.ResetButton_.Enable = ws.onIff(self.Model_.IsResetEnabled) ;
            isTrialSequenceModeRandom = isequal(self.Model_.TrialSequenceMode, 'random') ;
            self.MaximumRunLengthLabelledEdit_.Enable = ws.onIff(isTrialSequenceModeRandom) ;
            self.LaserTrialSpacingLabelledEdit_.Enable = ws.onIff(isTrialSequenceModeRandom) ;
            
            self.ToneFrequency1LabelledEdit_.Enable = ws.onIff(true) ;         
            self.ToneDelay1LabelledEdit_.Enable = ws.onIff(true) ;
            self.ToneDuration1LabelledEdit_.Enable = ws.onIff(true) ;
            self.DispenseDelay1LabelledEdit_.Enable = ws.onIff(true) ;
            self.DeliverPosition1XLabelledEdit_.Enable = ws.onIff(true) ; 
            self.DeliverPosition1YLabelledEdit_.Enable = ws.onIff(true) ; 
            self.DeliverPosition1ZLabelledEdit_.Enable = ws.onIff(true) ;  
            self.DispensePosition1XLabelledEdit_.Enable = ws.onIff(true) ;                   
            self.DispensePosition1YLabelledEdit_.Enable = ws.onIff(true) ;                   
            self.DispensePosition1ZLabelledEdit_.Enable = ws.onIff(true) ;                   
            
            self.ToneFrequency2LabelledEdit_.Enable = ws.onIff(true) ;             
            self.ToneDelay2LabelledEdit_.Enable = ws.onIff(true) ;
            self.ToneDuration2LabelledEdit_.Enable = ws.onIff(true) ;
            self.DispenseDelay2LabelledEdit_.Enable = ws.onIff(true) ;
            self.DeliverPosition2XLabelledEdit_.Enable = ws.onIff(true) ; 
            self.DeliverPosition2YLabelledEdit_.Enable = ws.onIff(true) ;    
            self.DeliverPosition2ZLabelledEdit_.Enable = ws.onIff(true) ;      
            self.DispensePosition2XLabelledEdit_.Enable = ws.onIff(true) ;
            self.DispensePosition2YLabelledEdit_.Enable = ws.onIff(true) ;
            self.DispensePosition2ZLabelledEdit_.Enable = ws.onIff(true) ;
        end             
        
        function result = get.FigurePosition(self)
            result = self.Figure_.Position ;
        end
        
        function syncFigurePosition(self) 
            % This moves the figure s.t. it's upper left corner
            % is in the same position as the upper left corner of
            % the on-screen rectangel defined by the models' SavedFigurePosition.
            % This is better, b/c sometimes we change the user class such that the 
            % figure size changes, and this will work better with old protocol files
            model = self.Model_ ;
            if model.IsFigurePositionSaved ,
                position = model.SavedFigurePosition ;
                upperLeftXY = [position(1) position(2)+position(4)] ;
                ws.positionFigureUpperLeft(self.Figure_, upperLeftXY) ;
            end               
        end
    end  % public methods block    
    
    methods (Access=private)
        function layout_(self)
            figureWidth = 344 ;
            figureHeight = 610 ;
            
            firstRowYBaseline = figureHeight - 32 ;
            defaultYSpacing = 30 ;
            sharedBlockXBaseline = 180 ;
            condition1XBaseline = 120 ;
            condition2XBaseline = condition1XBaseline + 120 ;
            popupMenuWidth = 80 ;
            editWidth = 60 ;
            belowFirstRowExtraYSpace = 16 ;
            
            belowSharedBlockExtraYSpace = 16 ;
            belowConditionLabelsYSpace = 20 ;
            modePopupXOffset = 60 ;
            %returnDelayXOffset = 240 ;
            resetButtonXOffset = 270 ;
            
            ws.resizeLeavingUpperLeftFixedBang(self.Figure_, [figureWidth figureHeight]) ;
            
            yOffset = firstRowYBaseline ;
            ws.positionPopupmenuAndLabelBang(self.TrialSequenceModeLabel_, ...
                                             self.TrialSequenceModePopupMenu_, ...
                                             modePopupXOffset, ...
                                             yOffset-1, ...
                                             popupMenuWidth) ;
            self.ResetButton_.Position(1:2) = [resetButtonXOffset yOffset] ;
            
            % Shared block
            yOffset = yOffset - defaultYSpacing - belowFirstRowExtraYSpace ;
            self.ReturnDelayLabelledEdit_.Position(1:2) = [sharedBlockXBaseline yOffset] ;
            self.ReturnDelayLabelledEdit_.Position(3)   = editWidth ;
            
            yOffset = yOffset - defaultYSpacing ;
            self.TapCountLabelledEdit_.Position(1:2) = [sharedBlockXBaseline yOffset] ;
            self.TapCountLabelledEdit_.Position(3)   = editWidth ;
            
            yOffset = yOffset - defaultYSpacing ;
            self.DispenseSpeedXLabelledEdit_.Position(1:2) = [sharedBlockXBaseline yOffset] ;
            self.DispenseSpeedXLabelledEdit_.Position(3)   = editWidth ;
            
            yOffset = yOffset - defaultYSpacing ;
            self.DispenseSpeedYLabelledEdit_.Position(1:2) = [sharedBlockXBaseline yOffset] ;
            self.DispenseSpeedYLabelledEdit_.Position(3)   = editWidth ;
            
            yOffset = yOffset - defaultYSpacing ;
            self.DispenseSpeedZLabelledEdit_.Position(1:2) = [sharedBlockXBaseline yOffset] ;
            self.DispenseSpeedZLabelledEdit_.Position(3)   = editWidth ;
            
            yOffset = yOffset - defaultYSpacing ;
            self.MaximumRunLengthLabelledEdit_.Position(1:2) = [sharedBlockXBaseline yOffset] ;
            self.MaximumRunLengthLabelledEdit_.Position(3)   = editWidth ;
            
            yOffset = yOffset - defaultYSpacing ;
            self.LaserTrialSpacingLabelledEdit_.Position(1:2) = [sharedBlockXBaseline yOffset] ;
            self.LaserTrialSpacingLabelledEdit_.Position(3)   = editWidth ;
            
            % Two-column part
            yOffset = yOffset - defaultYSpacing - belowSharedBlockExtraYSpace ;
            self.Condition1Label_.Position(1:2) = [condition1XBaseline yOffset] ;
            self.Condition2Label_.Position(1:2) = [condition2XBaseline yOffset] ;
                        
            yOffset = yOffset - belowConditionLabelsYSpace ;
            self.ToneFrequency1LabelledEdit_.Position(1:2) = [condition1XBaseline yOffset] ;
            self.ToneFrequency1LabelledEdit_.Position(3)   = editWidth ;
            self.ToneFrequency2LabelledEdit_.Position(1:2) = [condition2XBaseline yOffset] ;
            self.ToneFrequency2LabelledEdit_.Position(3)   = editWidth ;
            
            yOffset = yOffset - defaultYSpacing ;
            self.ToneDelay1LabelledEdit_.Position(1:2) = [condition1XBaseline yOffset] ;
            self.ToneDelay1LabelledEdit_.Position(3)   = editWidth ;
            self.ToneDelay2LabelledEdit_.Position(1:2) = [condition2XBaseline yOffset] ;
            self.ToneDelay2LabelledEdit_.Position(3)   = editWidth ;
            
            yOffset = yOffset - defaultYSpacing ;
            self.ToneDuration1LabelledEdit_.Position(1:2) = [condition1XBaseline yOffset] ;
            self.ToneDuration1LabelledEdit_.Position(3)   = editWidth ;
            self.ToneDuration2LabelledEdit_.Position(1:2) = [condition2XBaseline yOffset] ;
            self.ToneDuration2LabelledEdit_.Position(3)   = editWidth ;
            
            yOffset = yOffset - defaultYSpacing ;
            self.DispenseDelay1LabelledEdit_.Position(1:2) = [condition1XBaseline yOffset] ;
            self.DispenseDelay1LabelledEdit_.Position(3)   = editWidth ;
            self.DispenseDelay2LabelledEdit_.Position(1:2) = [condition2XBaseline yOffset] ;
            self.DispenseDelay2LabelledEdit_.Position(3)   = editWidth ;
            
            yOffset = yOffset - defaultYSpacing ;
            self.DeliverPosition1XLabelledEdit_.Position(1:2) = [condition1XBaseline yOffset] ;
            self.DeliverPosition1XLabelledEdit_.Position(3)   = editWidth ;
            self.DeliverPosition2XLabelledEdit_.Position(1:2) = [condition2XBaseline yOffset] ;
            self.DeliverPosition2XLabelledEdit_.Position(3)   = editWidth ;
            
            yOffset = yOffset - defaultYSpacing ;
            self.DeliverPosition1YLabelledEdit_.Position(1:2) = [condition1XBaseline yOffset] ;
            self.DeliverPosition1YLabelledEdit_.Position(3)   = editWidth ;
            self.DeliverPosition2YLabelledEdit_.Position(1:2) = [condition2XBaseline yOffset] ;
            self.DeliverPosition2YLabelledEdit_.Position(3)   = editWidth ;
            
            yOffset = yOffset - defaultYSpacing ;
            self.DeliverPosition1ZLabelledEdit_.Position(1:2) = [condition1XBaseline yOffset] ;
            self.DeliverPosition1ZLabelledEdit_.Position(3)   = editWidth ;
            self.DeliverPosition2ZLabelledEdit_.Position(1:2) = [condition2XBaseline yOffset] ;
            self.DeliverPosition2ZLabelledEdit_.Position(3)   = editWidth ;
            
            yOffset = yOffset - defaultYSpacing ;
            self.DispensePosition1XLabelledEdit_.Position(1:2) = [condition1XBaseline yOffset] ;
            self.DispensePosition1XLabelledEdit_.Position(3)   = editWidth ;
            self.DispensePosition2XLabelledEdit_.Position(1:2) = [condition2XBaseline yOffset] ;
            self.DispensePosition2XLabelledEdit_.Position(3)   = editWidth ;
            
            yOffset = yOffset - defaultYSpacing ;
            self.DispensePosition1YLabelledEdit_.Position(1:2) = [condition1XBaseline yOffset] ;
            self.DispensePosition1YLabelledEdit_.Position(3)   = editWidth ;
            self.DispensePosition2YLabelledEdit_.Position(1:2) = [condition2XBaseline yOffset] ;
            self.DispensePosition2YLabelledEdit_.Position(3)   = editWidth ;
            
            yOffset = yOffset - defaultYSpacing ;
            self.DispensePosition1ZLabelledEdit_.Position(1:2) = [condition1XBaseline yOffset] ;
            self.DispensePosition1ZLabelledEdit_.Position(3)   = editWidth ;
            self.DispensePosition2ZLabelledEdit_.Position(1:2) = [condition2XBaseline yOffset] ;
            self.DispensePosition2ZLabelledEdit_.Position(3)   = editWidth ;
        end        
    end  % private methods block    
    
end  % classdef
